
package com.demo.mydemo.jdk.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloServiceImpl", targetNamespace = "http://server.jdk.mydemo.demo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://server.jdk.mydemo.demo.com/", className = "com.demo.mydemo.jdk.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://server.jdk.mydemo.demo.com/", className = "com.demo.mydemo.jdk.client.SayHelloResponse")
    @Action(input = "http://server.jdk.mydemo.demo.com/HelloServiceImpl/sayHelloRequest", output = "http://server.jdk.mydemo.demo.com/HelloServiceImpl/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.demo.mydemo.jdk.client.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello2", targetNamespace = "http://server.jdk.mydemo.demo.com/", className = "com.demo.mydemo.jdk.client.SayHello2")
    @ResponseWrapper(localName = "sayHello2Response", targetNamespace = "http://server.jdk.mydemo.demo.com/", className = "com.demo.mydemo.jdk.client.SayHello2Response")
    @Action(input = "http://server.jdk.mydemo.demo.com/HelloServiceImpl/sayHello2Request", output = "http://server.jdk.mydemo.demo.com/HelloServiceImpl/sayHello2Response")
    public List<User> sayHello2(
        @WebParam(name = "arg0", targetNamespace = "")
        List<User> arg0);

}
