# branches:
#   only:
#     - master

language: go

go:
  - "1.11"

before_install: 
  - sudo apt-get install oracle-java8-set-default
  - echo $JAVA_HOME

install: true

script:
  - sudo chmod +x ./test.sh
  - ./test.sh
