# branches:
#   only:
#     - master

language: go

go:
  - "1.11"

install:
  - curl -R -O http://www.lua.org/ftp/lua-5.3.4.tar.gz
  - tar zxf lua-5.3.4.tar.gz
  - cd lua-5.3.4
  - make linux test
  - cd ..
  - sudo ln -s $PWD/lua-5.3.4/src/lua /usr/bin/lua
  - sudo ln -s $PWD/lua-5.3.4/src/luac /usr/bin/luac
  - luac -v

script:
  - sudo chmod +x ./test.sh
  - ./test.sh
