server:
  port: 1688

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fund?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=true
    username: root
    password: rootroot

##-------mybatis plus 配置----------------start----------------------
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  ##-------mybatis plus 配置----------------end----------------------

#  # log config
#logging:
#  config=classpath:logback.xml
#
#xxl:
#  job:
#    admin:
#      addresses: http://127.0.0.1:1888/xxl-job-admin
#      accessToken: default_token
#  executor:
#    appname: xxl-job-executor-sample
#    port: 9999
#    logpath: ./jobhandler
#    logretentiondays: 2
