server:
  port: 1688

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fund?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=true
    username: root
    password: rootroot

##-------mybatis plus 配置----------------start----------------------
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
##-------mybatis plus 配置----------------end----------------------